export enum FormActionTypes {
    UPDATE_PARCELAS = "UPDATE_PARCELAS",
    UPDATE_GARANTIA = "UPDATE_GARANTIA",
    UPDATE_VALOR_GARANTIA = "UPDATE_VALOR_GARANTIA",
    UPDATE_VALOR_EMPRESTIMO = "UPDATE_VALOR_EMPRESTIMO",
    UPDATE_MIN_GARANTIA = "UPDATE_MIN_GARANTIA",
    UPDATE_MAX_GARANTIA = "UPDATE_MAX_GARANTIA",
    UPDATE_MIN_EMPRESTIMO = "UPDATE_MIN_EMPRESTIMO",
    UPDATE_MAX_EMPRESTIMO = "UPDATE_MAX_EMPRESTIMO",
    CALCULA_TOTAL_A_PAGAR = "CALCULA_TOTAL_A_PAGAR",
    CALCULA_VALOR_DA_PARCELA = "CALCULA_VALOR_DA_PARCELA",
} 